services:

  smssender:
    build:
      context: ./smssender
    container_name: smssender
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - redis
      - kafka

  smsconsumer:
    build:
      context: ./smsconsumer
    container_name: smsconsumer
    ports:
      - "8081:8081"
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - DB_NAME=sms_db
      - COLLECTION_NAME=logs
    depends_on:
      - kafka
      - mongodb
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_kraft:/var/lib/kafka/data
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'kafka-cluster'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kafka-combined-logs  

volumes:
  redis_data:
  mongodb_data:
  kafka_kraft: